config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  get '/posts/new', to: 'posts#new', as: 'create_post'
  post '/posts/new', to: 'posts#create'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'post'
  post '/users/:user_id/posts/:id/', to: 'posts#create_comment'
  post '/users/:user_id/posts/:id/likes', to: 'posts#create_like', as: 'like'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_save :update_comments_counter

  belongs_to :post, class_name: 'Post', foreign_key: :post_id
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  after_save :update_likes_counter

  belongs_to :author, class_name: 'User'
  belongs_to :post

  def update_likes_counter
    post.update(likes_counter: post.likes.all.length)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_posts_counter

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, allow_blank: false, allow_nil: false, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.update(posts_counter: author.posts.size)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates_presence_of :name
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(id: :asc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user = User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    post = Post.find(params[:post_id])
    comment = Comment.create(author: current_user, post: comment_params)
    return unless comment.save

    redirect_to user_post_path(current_user.id, post.id), notice: 'Comment saved'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]
    if @like.save!
      redirect_to user_posts_path(current_user)
    else
      redirect_to :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comment = Comment.new
    @like = Like.new
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:id])
    @comment.author = current_user
    redirect_to post_path if @comment.save
  end

  def create_like
    @like = Like.new(author: current_user, post: Post.find(params[:id]))
    redirect_to post_path if @like.save
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0
    return unless @post.save

    redirect_to posts_new_path
    flash[:success] = 'Post have been saved successfully'
  end

  def new
    @post = Post.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(:id)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class='post-item'>
    <h3>Post #<%= post.id %>
        <%= link_to post.title,user_post_path(@user, post) %>
    </h3>
    <p><%= post.text%></p>
    <div class='post-details'>
        <p>Comments: <%= post.comments.size %></p>
        <p>Likes: <%= post.likes.size%></p>
    </div>
</div>

app/views/posts/index.html.erb
<section class='user-posts'>
    <nav>
        <%= render 'users/user', user: @user %>
    </nav>
    <% @user.recent_posts.each_with_index do |post, id| %>
        <div class='post-user'>
            <%= render 'posts/post', post: post %>
            <div class='user-comments'>
                <% post.recent_comments.each do |comment| %>
                    <p>
                        <strong>
                            <%= comment.author.name %>
                        </strong>
                        :<%= comment.text %>
                    </p>
                <% end %>
            </div>
        </div>
    <% end %>
    <div class="pagination">
        <a href="#">Prev</a>
        <a href="#">1</a>
        <a href="#">Next</a>
  </div>
</section>

app/views/posts/new.html.erb
<div class="post-container">
  <h1>Create New Post</h1>

  <%= form_with model: @post, url: posts_new_path, method: :post, scope: :post do |f| %>
    <div class="column">
      <%= f.text_field :title, placeholder: 'Title of post', class: 'text-input' %>
      <%= f.text_area :text,placeholder: 'Description of post' %>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="my-comment">
  <div class="comment-bio">
      <div class='comment-header'>
        <p class='title'><%= @post.title %> by <%= @user.name %></p>
        <div class='comment-details'>
            <p>Comments: <%= @post.comments.size %></p>
            <p>Likes: <%= @post.likes.size %></p>
        </div>
      </div>
      <p class="comment-text"><%= @post.text%></p>
  </div>
  <div class="comments">
      <div class="comment-item">
        <% @post.comments.includes(:author).each do |comment|%>
            <p><%= comment.author.name %> <%= comment.text %></p>
        <% end %>
      </div>
  </div>
  <div class='post-feature'>
    <%= form_with model: @like, url: like_path, method: :post do |f| %>
        <%= f.submit "Like post", class: "like-post" %>
    <% end %>
    <%= form_with model: @comment, url: post_path, method: :post, scope: :comment do |f| %>
      <div class="comment-section">
        <%= f.text_area :text, placeholder: "Add Comment", class: "comment" %>
        <%= f.submit "Comment", class: "submit-comment" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class='user-item'>
    <img src="<%= user.photo %>" alt='avatar-<%= user.name%>' class='user-avatar'><br>
    <div class='user-description'>
        <h2 class='user-name'>
            <%= link_to user.name , user %>
        </h2>
        <span class='post-number'>Post counter: <%= user.posts_counter == nil ? 0 : user.posts_counter %></span>
    </div>
</div>

app/views/users/index.html.erb
<section class='users-list'>
  <% @users.each do |user| %>
    <%= render "users/user", user: user %>
  <% end %>

  <div>
    <%= link_to create_post_path do %>
      <button class="create-post">create post</button>
    <%end%>
  </div>
</section>

app/views/users/show.html.erb
<section class='user-details'>
    <nav>
        <%= render "users/user", user: @user %>
    </nav>
    <div class='bio'>
        <h3>Bio</h3>
        <p><%= @user.bio%></p>
    </div>
    <% @user.recent_posts.each do |post| %>
        <%= render 'posts/post', post: post %>
    <% end %>
    <button type="button" class="see-all-posts">
        <%= link_to "See All Posts", user_posts_path(@user) %>
    </button>
</section>